version: '3.9'

volumes:
  dbdata:
  redisdata:

services:
  node:
    image: node:16.10-alpine
    tty: true
    volumes:
      - ./ui:/app

  web:
    build:
      context: deployment/local/nginx
    ports:
      - '8080:80'
    depends_on:
      - app
    volumes:
      - ./app/public:/var/www
      - ./deployment/local/nginx/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build:
      context: .
      dockerfile: deployment/local/php/Dockerfile
    env_file:
      - .env
    volumes:
      - ./app:/var/www
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      - ~/.composer-docker/cache:/root/.composer/cache
    depends_on:
      - db
      - redis

  db:
    image: postgres:13.4-alpine
    ports:
      - '8081:5432'
    environment:
      POSTGRES_DB: roadsurfer
      POSTGRES_USER: roadsurfer
      POSTGRES_PASSWORD: forge
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: redis:5.0.7
    volumes:
      - redisdata:/data
    ports:
      - '8082:6379'
